### ISSUE TITLE
과제 질문

### ISSUE THREAD

**Issue by woong97** [mnskim/wmt_baseline#1]
조교님 제가 과제를 정확히 이해하지 못하고 있는 것 같습니다.
코드에서 모델이랑 토크나이저, 그리고 train class 다 huggingface transformer를 사용하고 있는데, 저희는 어떤 걸 수정하여 performance를 높이는 것인가요? 모델 코드를 저희가 직접 짜는것이 아니라 transformer 모델을 사용하는 것인가요?

**Comment by mnskim** [comment]
안녕하세요, 

모델 수정도 가능합니다만, 이부분이 어려울경우를 감안 해서, 꼭 모델코드를 수정해야 하는 요구사항은 없습니다. 그리고 원하는/적용 가능한 기법들을 자유롭게 사용해보셔도 됩니다.
모델코드를 크게 변경 하지않고, data augmentation이나 backtranslation등등, 데이터쪽으로 성능 개선을 해보시는것도 가능합니다!

**Comment by woong97** [comment]
답변 감사합니다!! 질문이 더 있는데요!
1. 그럼 모델을 수정하고 싶다면, 모델을 아예 바꾸고 그에 따른 bleu score 계산하는 방법이나 result.json 저장하는 것 역시 스스로 다 만들어야 하는 것인거죠?
2. data2_terminology랑 data_2 폴더에서 train.tsv는 구성이 다른데 어떻게 다른건가요??
3. data augmentation라는 것은 , 새로운 데이터를 다른곳에서 가져와서 주어진 train.tsv를 늘리는것은 안되고, 주어진 train.tsv 안에서 data augmentaition을 하라는 말씀이신거죠?

**Comment by mnskim** [comment]
안녕하세요,

1. 만약에 모델이 변경됬을때 (예를들어 huggingface 아닌 모델인 경우), compute_metric을 통해 bleu 계산이 불가능한 경우는, 다른 라이브러리 등을 통해서 직접 계산하셔도 됩니다. 

    bleu계산은 다른 widely used 라이브러리가 많아서, 자유롭게 사용하셔도 되고, 최종적으로 result.json에 bleu가 잘 표기되면 됩니다.

2. data_2 와 data_2_terminology의 차이는 608개의 terminologies (`terminologies/terminologies.fr.txt` 에서 추출한) pair가 추가된 점인데요, 이부분에 버그가 있었어서 업데이트 해놓았습니다. 

    (추가된 `diffcheck.py` 를 실행해서, 두 파일의 차이를 확인하실수 있습니다.)

3. 전자는 in-domain 데이터를 추가하는것이라고 볼수 있는데요, (예를들어 medline과 taus에서 몇십만개 학습 example을 추가) 이 방법보다는,

    in-domain데이터는 한정적이라고 보고, out-of-domain 데이터를 사용한다거나, terminology를 사용한다거나, 주어진 train.tsv를 가지고 data augmentation을 하는 방법 등을 추천드립니다!
