### ISSUE TITLE
bleu 성능 질문

### ISSUE THREAD

**Issue by woong97** [mnskim/wmt_baseline#2]
조교님 안녕하세요! predict_result.json에 나오는 predict_bleu에 값에 대한 질문이 있는데요!
저는 조교님이 알려주신대로 data augmentation, back translation을 사용해봤는데 오히려 성능이 떨어지더라구요...
codalab-competition에 올리신 bleu 38.87 나온 모델은 조교님이 코랩 링크 올려주신 대로 돌렸을 때 나오는 모델인가요

**Comment by mnskim** [comment]
안녕하세요, 
result 페이지 왼쪽에 나오는 bleu는 dev와 test의 평균입니다, [result page](https://competitions.codalab.org/competitions/31670#results) 에서 dev와 test 각각 스코어들 확인해보실수 있습니다 (**cerberusd is the TA baseline**). 

submit하실때는 predict_results.json (test 결과) 과 eval_results.json (dev 결과) 둘 다가 필요한데요, 원래는 test 와 dev의 평균으로 평가를 할 계획이었는데, 
test결과로만 평가하는걸로 변경이 되서, TA baseline의 test bleu (37.6491 bleu (3 epochs, use terminology)) 와만 비교해주시면 됩니다.  

[submission page](https://competitions.codalab.org/competitions/31670#learn_the_details-evaluation) 에 결과 submit 하는 방법을 업데이트 해놓았으니 참조해주시고, submission 에 문제있으면 알려주세요!
