### ISSUE TITLE
Dev, Test set 수정 관련 문의.

### ISSUE THREAD

**Issue by JIeunAmy** [mnskim/wmt_baseline#3]
조교님, 안녕하세요.

제가 주어진 terminology(608개)에 해당하는 phrase에 대해서 tagging을 하는 방식으로 data augumentation을 수행하여 학습을 하였는데,
이 방식을 dev data와 test data에도 적용 하여 성능을 측정하였습니다.
저는 dev랑 test에도 tokenizing을 사용하듯이 tagging도 적용해도 된다고 생각하여 그렇게 하였는데, 인정되는 방식이 맞을까요?
dev와 test data는 동일한 파일로 하였고, 실행 코드 내에서 tagging을 적용하였습니다!

**Comment by mnskim** [comment]
안녕하세요,

dev/test에 대한 해당 terminology tagging은 인정되는 방식이 맞습니다. dev/test관련 유의사항은:
1) dev/test가 학습데이터에 포함되지 않고, 
2) 원본 dev/test 파일에서 example들이 drop/add 되지 않으면 됩니다 (dev/test data 동일한 파일 사용) 

이 외의 방법은, dev/test에도 자유롭게 적용하실수 있습니다!

**Comment by JIeunAmy** [comment]
답변 감사합니다!ㅎㅎ
